name: Build Image

on:
  workflow_call:
    inputs:
      image:
        description: Image directory to build
        required: true
        type: string

jobs:
  build:
    name: Build (${{ inputs.image }})
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.sha }}

      - name: Prepare image metadata
        id: meta
        run: |
          version=$(grep '^FROM' "${{ inputs.image }}/Dockerfile" | tail -1 | sed 's/.*://')
          echo "image_ref=ghcr.io/trly/${{ inputs.image }}:$version" >> "$GITHUB_OUTPUT"

      - name: Build image
        run: docker build -t "${{ steps.meta.outputs.image_ref }}" "${{ inputs.image }}"

      - name: Archive image
        run: docker save "${{ steps.meta.outputs.image_ref }}" | gzip > "${{ runner.temp }}/image.tar.gz"

      - name: Write image metadata
        run: printf '%s\n' '${{ inputs.image }}' > '${{ runner.temp }}/image.txt'

      - name: Upload image artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: docker-image-${{ inputs.image }}
          path: |
            ${{ runner.temp }}/image.tar.gz
            ${{ runner.temp }}/image.txt
          retention-days: 1
